apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.eventGenerator.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator-app
  template:
    metadata:
      labels:
        app: generator-app
    spec:
      containers:
      - name: {{ .Values.eventGenerator.name }}
        image: {{ .Values.eventGenerator.repository }}
        ports:
        - containerPort: {{ .Values.eventGenerator.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.eventGenerator.name }}
  labels:
    app: generator-app
spec:
  type: ClusterIP
  ports:
  - name: generator-app-port
    port: {{ .Values.eventGenerator.port }}
    protocol: TCP
  selector:
    app: generator-app
